# Generated by Django 5.1.4 on 2024-12-12 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_simpleuser_middle_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleUser',
        ),
        migrations.RemoveField(
            model_name='request',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='request',
            name='date_time',
        ),
        migrations.AddField(
            model_name='request',
            name='preferred_date_time',
            field=models.DateTimeField(null=True, verbose_name='Дата и время'),
        ),
        migrations.AddField(
            model_name='request',
            name='service',
            field=models.CharField(default='Не указано', max_length=255, verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'Новая заявка'), ('in_progress', 'В работе'), ('completed', 'Услуга оказана'), ('canceled', 'Услуга отменена')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='request',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='request',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отмены'),
        ),
        migrations.AlterField(
            model_name='request',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта')], max_length=10, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
