# Generated by Django 5.1.4 on 2024-12-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_simpleuser_remove_request_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='service',
            field=models.CharField(choices=[('general_cleaning', 'Общий клининг'), ('deep_cleaning', 'Генеральная уборка'), ('post_construction_cleaning', 'Послестроительная уборка'), ('dry_cleaning', 'Химчистка')], max_length=100, verbose_name='Услуга'),
        ),
    ]
